scenario_parameters:
  time_step: 60
  MJD_start: 59348.916238425903430
  MJD_end: 59349.916238425903430
  max_time_step: 60
  output_directory: out/

initial_orbtial_parameters:
  dim_state: 6
  initial_state: [-21081956.13731487, 36515083.37219601, 52036.005860564575, -2662.7359116769585, -1537.33399910928, 3.7945487330459287]
  initial_state_type: ECI

propagator_truth_settings:
  # earth_gravity_model_order: 2
  # earth_gravity_model_degree: 2
  # third_body_attraction: false
  # third_body_sun: false
  # third_body_moon: false
  # solid_earth_tide: false
  # ocean_tide_loading: false
  # solar_radiation_pressure: false
  # atmospheric_drag: false
  # relativity_effect: false
  srpCoef: 1.23
  srpArea : 8.73
  dragCoef: 2.0
  dragArea : 4.091655
  satMass : 961.831

supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/linux_p1550p2650.440
  ERP_file: ./auxdata/cod21587.erp
