scenario_parameters:
  time_step: 60
  MJD_start: 59348.9162384259
  MJD_end: 59349.9995717593
  max_time_step: 60
  output_directory: out/out_prop
initial_orbtial_parameters:
  dim_state: 6
  initial_state:
  - -5447560.892049404
  - -4956657.291930266
  - -2305805.5924205882
  - 3491.012988530725
  - -945.945974206399
  - -6211.507133252835
  initial_state_type: ECI
propagator_truth_settings:
  earth_gravity_model_order: 100
  earth_gravity_model_degree: 100
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: true
  ocean_tide_loading: true
  solar_radiation_pressure: true
  atmospheric_drag: false
  relativity_effect: true
  srpCoef: 1.23
  srpArea: 8.73
  dragCoef: 2.0
  dragArea: 4.091655
  satMass: 961.831
supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/linux_p1550p2650.440
  ERP_file: ./auxdata/cod21587.erp
